# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180503_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
