# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180503_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
