# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180508_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_id', models.IntegerField()),
                ('contact_start_date', models.DateTimeField(null=True)),
                ('contact_end_date', models.DateTimeField(null=True)),
                ('Commission_rate', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_type', models.CharField(max_length=4)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contract')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='station_id',
        ),
        migrations.AddField(
            model_name='order',
            name='station_id_borrow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='station_id_borrow', to='accounts.Station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='station_id_return',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='station_id_return', to='accounts.Station'),
            preserve_default=False,
        ),
    ]
