# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180512_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='station_type',
        ),
        migrations.AddField(
            model_name='station',
            name='model_name',
            field=models.CharField(default='X920', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='provider',
            field=models.CharField(default='XiongDaDa', max_length=30),
            preserve_default=False,
        ),
    ]
