# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180512_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('PIC', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=7)),
                ('tel', models.CharField(max_length=12)),
                ('address_country', models.CharField(max_length=30)),
                ('address_prefecture', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_detail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('PIC', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=7)),
                ('tel', models.CharField(max_length=12)),
                ('address_country', models.CharField(max_length=30)),
                ('address_prefecture', models.CharField(max_length=30)),
                ('address_city', models.CharField(max_length=30)),
                ('address_detail', models.CharField(max_length=100)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
    ]
