# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180512_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='battery_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='station_id_return',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_id_return', to='accounts.Station'),
        ),
    ]
